ICMP_MESSAGE_PORT = 'port'
ICMP_MESSAGE_DATA = 'data'
ICMP_MESSAGE_MAGIC = 'ICMPTUNNELING'

ICMP_PORT_FIELD = 'seq'
ICMP_CONNECT_MESSEGE_CODE = 250
ICMP_CONNECT_ACK_MESSEGE_CODE = 251
ICMP_DATA_MESSEGE_CODE = 252
ICMP_FRAGMENTED_DATA_MESSEGE_CODE = 253
ICMP_FRAGMENTED_DATA_DONE_MESSEGE_CODE = 254

ICMP_CLIENT_ID = 8
ICMP_SERVER_ID = 0

ICMP_SOCKET_SNIFF_TIMEOUT = 15
MAX_ICMP_MESSAGE_SIZE = 1024

ICMP_CONNECT_FILTER = 'icmp[icmpcode]=={0}'.format(str(ICMP_CONNECT_MESSEGE_CODE))
ICMP_CONNECT_ACK_FILTER = 'icmp[icmpcode]=={0}'.format(str(ICMP_CONNECT_ACK_MESSEGE_CODE))
ICMP_DATA_FILTER = 'icmp[icmpcode]=={0} or icmp[icmpcode]=={1} or icmp[icmpcode]=={2}'.format(str(ICMP_DATA_MESSEGE_CODE), str(ICMP_FRAGMENTED_DATA_MESSEGE_CODE), str(ICMP_FRAGMENTED_DATA_DONE_MESSEGE_CODE))
